name: Fly Deploy
on:
  push:
    branches:
      - main # change to main
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: checkout code
        uses: DonaldC-HKBU/Lab3-4@main

      - name:  Deploy to Fiy.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
